### ISSUE TITLE
[FEATURE] Add the option to select a desired user by default

### ISSUE THREAD

**Issue by DubiousCactus** [naueramant/lightdm-webkit-sequoia#5]
Hi !

For my own personal use, I have modified your code to allow me to select the account I desire by default using the config file. I also added an option to skip the list and directly go to the password prompt.

I would be very happy if you'd like to include my changes, therefore I created a pull request :)

Thanks for your work !

Pull request: #4

**Comment by naueramant** [comment]
Sure, I will review the request asap :).

**Comment by naueramant** [comment]
Implementation in pull request #4 merged
